# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _hello
else:
    import _hello

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _hello.delete_SwigPyIterator

    def value(self):
        return _hello.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _hello.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _hello.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _hello.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _hello.SwigPyIterator_equal(self, x)

    def copy(self):
        return _hello.SwigPyIterator_copy(self)

    def next(self):
        return _hello.SwigPyIterator_next(self)

    def __next__(self):
        return _hello.SwigPyIterator___next__(self)

    def previous(self):
        return _hello.SwigPyIterator_previous(self)

    def advance(self, n):
        return _hello.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _hello.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _hello.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _hello.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _hello.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _hello.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _hello.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _hello:
_hello.SwigPyIterator_swigregister(SwigPyIterator)

class MyString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    npos = _hello.MyString_npos

    def __init__(self, *args):
        _hello.MyString_swiginit(self, _hello.new_MyString(*args))
    __swig_destroy__ = _hello.delete_MyString

    def equall_c(self, c):
        return _hello.MyString_equall_c(self, c)

    def equall_std_string(self, std_string):
        return _hello.MyString_equall_std_string(self, std_string)

    def equall_char_array(self, cchar_array):
        return _hello.MyString_equall_char_array(self, cchar_array)

    def __str__(self):
        return _hello.MyString___str__(self)

    def __iadd__(self, *args):
        return _hello.MyString___iadd__(self, *args)

    def __add__(self, *args):
        return _hello.MyString___add__(self, *args)

    def __eq__(self, left):
        return _hello.MyString___eq__(self, left)

    def __ne__(self, left):
        return _hello.MyString___ne__(self, left)

    def __lt__(self, left):
        return _hello.MyString___lt__(self, left)

    def __gt__(self, left):
        return _hello.MyString___gt__(self, left)

    def __le__(self, left):
        return _hello.MyString___le__(self, left)

    def __ge__(self, left):
        return _hello.MyString___ge__(self, left)

    def __setitem__(self, i, c):
        return _hello.MyString___setitem__(self, i, c)

    def __getitem__(self, i):
        return _hello.MyString___getitem__(self, i)

    def c_str(self):
        return _hello.MyString_c_str(self)

    def c_str2(self):
        return _hello.MyString_c_str2(self)

    def data(self):
        return _hello.MyString_data(self)

    def length(self):
        return _hello.MyString_length(self)

    def size(self):
        return _hello.MyString_size(self)

    def empty(self):
        return _hello.MyString_empty(self)

    def capacity(self):
        return _hello.MyString_capacity(self)

    def shrink_to_fit(self, cap):
        return _hello.MyString_shrink_to_fit(self, cap)

    def clear(self):
        return _hello.MyString_clear(self)

    def find(self, *args):
        return _hello.MyString_find(self, *args)

    def append(self, *args):
        return _hello.MyString_append(self, *args)

    def insert(self, *args):
        return _hello.MyString_insert(self, *args)

    def erase(self, index, count):
        return _hello.MyString_erase(self, index, count)

    def replace(self, *args):
        return _hello.MyString_replace(self, *args)

    def substr(self, *args):
        return _hello.MyString_substr(self, *args)

# Register MyString in _hello:
_hello.MyString_swigregister(MyString)



